### ISSUE TITLE
Compatibility with IE

### ISSUE THREAD

**Issue by rafatwork** [AverageMarcus/Truncatise#6]
Thank you for this great library.

I ran into an issue on IE. Truncatise uses the trimRight() function, which is not supported in IE. Check https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/TrimRight for more information.

Shimming it through https://github.com/es-shims/String.prototype.trimRight fixed my problem. You might want to include this in the library or at least mention it in the README.

**Comment by AverageMarcus** [comment]
Hi 👋 

That's a great idea to include the shim. I wasn't aware of the compatibility. I'll look to getting it included when I get the time. 

Thanks!

**Comment by AverageMarcus** [comment]
Fixed and released as 0.0.7 - https://www.npmjs.com/package/truncatise

**Comment by rafatwork** [comment]
@AverageMarcus Thanks, works like a charm!

**Comment by AverageMarcus** [comment]
🎉  Huzzah! Thanks for confirming! 👍
